#!/bin/sh

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

cd /

while :; do
  su -c 'PATH="$PATH":/apps '"$*" miner
  echo "Restarting in 30 seconds..."
  sleep 30
done
